// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: internal/pkg/internapi/internapi.proto

package internapi

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DNSResponse_Type int32

const (
	DNSResponse_ANSWER     DNSResponse_Type = 0
	DNSResponse_AUTHORITY  DNSResponse_Type = 1
	DNSResponse_ADDITIONAL DNSResponse_Type = 2
)

// Enum value maps for DNSResponse_Type.
var (
	DNSResponse_Type_name = map[int32]string{
		0: "ANSWER",
		1: "AUTHORITY",
		2: "ADDITIONAL",
	}
	DNSResponse_Type_value = map[string]int32{
		"ANSWER":     0,
		"AUTHORITY":  1,
		"ADDITIONAL": 2,
	}
)

func (x DNSResponse_Type) Enum() *DNSResponse_Type {
	p := new(DNSResponse_Type)
	*p = x
	return p
}

func (x DNSResponse_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DNSResponse_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_internapi_internapi_proto_enumTypes[0].Descriptor()
}

func (DNSResponse_Type) Type() protoreflect.EnumType {
	return &file_internal_pkg_internapi_internapi_proto_enumTypes[0]
}

func (x DNSResponse_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DNSResponse_Type.Descriptor instead.
func (DNSResponse_Type) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{3, 0}
}

// Batch question-response pairs.
type NewContentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []*DNSQuestionResponse `protobuf:"bytes,1,rep,name=content,proto3" json:"content,omitempty"`
}

func (x *NewContentRequest) Reset() {
	*x = NewContentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewContentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewContentRequest) ProtoMessage() {}

func (x *NewContentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewContentRequest.ProtoReflect.Descriptor instead.
func (*NewContentRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{0}
}

func (x *NewContentRequest) GetContent() []*DNSQuestionResponse {
	if x != nil {
		return x.Content
	}
	return nil
}

type DNSQuestionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Question *DNSQuestion   `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	Response []*DNSResponse `protobuf:"bytes,2,rep,name=response,proto3" json:"response,omitempty"`
}

func (x *DNSQuestionResponse) Reset() {
	*x = DNSQuestionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNSQuestionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSQuestionResponse) ProtoMessage() {}

func (x *DNSQuestionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSQuestionResponse.ProtoReflect.Descriptor instead.
func (*DNSQuestionResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{1}
}

func (x *DNSQuestionResponse) GetQuestion() *DNSQuestion {
	if x != nil {
		return x.Question
	}
	return nil
}

func (x *DNSQuestionResponse) GetResponse() []*DNSResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

// Same as dns.Question
type DNSQuestion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Qtype uint32 `protobuf:"varint,2,opt,name=qtype,proto3" json:"qtype,omitempty"`
}

func (x *DNSQuestion) Reset() {
	*x = DNSQuestion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNSQuestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSQuestion) ProtoMessage() {}

func (x *DNSQuestion) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSQuestion.ProtoReflect.Descriptor instead.
func (*DNSQuestion) Descriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{2}
}

func (x *DNSQuestion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSQuestion) GetQtype() uint32 {
	if x != nil {
		return x.Qtype
	}
	return 0
}

type DNSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rr     []byte                 `protobuf:"bytes,1,opt,name=rr,proto3" json:"rr,omitempty"` // packed dns.RR
	Expiry *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Type   DNSResponse_Type       `protobuf:"varint,3,opt,name=type,proto3,enum=internapi.DNSResponse_Type" json:"type,omitempty"`
}

func (x *DNSResponse) Reset() {
	*x = DNSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DNSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSResponse) ProtoMessage() {}

func (x *DNSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSResponse.ProtoReflect.Descriptor instead.
func (*DNSResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{3}
}

func (x *DNSResponse) GetRr() []byte {
	if x != nil {
		return x.Rr
	}
	return nil
}

func (x *DNSResponse) GetExpiry() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiry
	}
	return nil
}

func (x *DNSResponse) GetType() DNSResponse_Type {
	if x != nil {
		return x.Type
	}
	return DNSResponse_ANSWER
}

type ListKeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Questions []*DNSQuestion `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
}

func (x *ListKeysResponse) Reset() {
	*x = ListKeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListKeysResponse) ProtoMessage() {}

func (x *ListKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_internapi_internapi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListKeysResponse.ProtoReflect.Descriptor instead.
func (*ListKeysResponse) Descriptor() ([]byte, []int) {
	return file_internal_pkg_internapi_internapi_proto_rawDescGZIP(), []int{4}
}

func (x *ListKeysResponse) GetQuestions() []*DNSQuestion {
	if x != nil {
		return x.Questions
	}
	return nil
}

var File_internal_pkg_internapi_internapi_proto protoreflect.FileDescriptor

var file_internal_pkg_internapi_internapi_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x70, 0x69, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x4d, 0x0a, 0x11, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x4e, 0x53, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x22, 0x7d, 0x0a, 0x13, 0x44, 0x4e, 0x53, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x4e, 0x53, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x08, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x32, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x4e, 0x53, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x37, 0x0a, 0x0b, 0x44, 0x4e, 0x53, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x71, 0x74, 0x79, 0x70, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x44, 0x4e, 0x53,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x72, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x72, 0x72, 0x12, 0x32, 0x0a, 0x06, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x12, 0x2f, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x4e, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x31, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x4e, 0x53, 0x57, 0x45, 0x52, 0x10,
	0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x54, 0x59, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x44, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x41, 0x4c, 0x10, 0x02,
	0x22, 0x48, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x70, 0x69, 0x2e, 0x44, 0x4e, 0x53, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x09, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x32, 0x9c, 0x01, 0x0a, 0x09, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x41, 0x50, 0x49, 0x12, 0x44, 0x0a, 0x0a, 0x4e, 0x65, 0x77, 0x43,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x70, 0x69, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x49,
	0x0a, 0x10, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65,
	0x79, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x1b, 0x2e, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x40, 0x5a, 0x3e, 0x67, 0x6f, 0x2e,
	0x74, 0x69, 0x6d, 0x6f, 0x74, 0x68, 0x79, 0x67, 0x75, 0x2e, 0x6d, 0x65, 0x2f, 0x73, 0x74, 0x61,
	0x6e, 0x66, 0x6f, 0x72, 0x64, 0x2d, 0x63, 0x73, 0x32, 0x34, 0x34, 0x62, 0x2d, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_internapi_internapi_proto_rawDescOnce sync.Once
	file_internal_pkg_internapi_internapi_proto_rawDescData = file_internal_pkg_internapi_internapi_proto_rawDesc
)

func file_internal_pkg_internapi_internapi_proto_rawDescGZIP() []byte {
	file_internal_pkg_internapi_internapi_proto_rawDescOnce.Do(func() {
		file_internal_pkg_internapi_internapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_internapi_internapi_proto_rawDescData)
	})
	return file_internal_pkg_internapi_internapi_proto_rawDescData
}

var file_internal_pkg_internapi_internapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_internapi_internapi_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_pkg_internapi_internapi_proto_goTypes = []interface{}{
	(DNSResponse_Type)(0),         // 0: internapi.DNSResponse.Type
	(*NewContentRequest)(nil),     // 1: internapi.NewContentRequest
	(*DNSQuestionResponse)(nil),   // 2: internapi.DNSQuestionResponse
	(*DNSQuestion)(nil),           // 3: internapi.DNSQuestion
	(*DNSResponse)(nil),           // 4: internapi.DNSResponse
	(*ListKeysResponse)(nil),      // 5: internapi.ListKeysResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 7: google.protobuf.Empty
}
var file_internal_pkg_internapi_internapi_proto_depIdxs = []int32{
	2, // 0: internapi.NewContentRequest.content:type_name -> internapi.DNSQuestionResponse
	3, // 1: internapi.DNSQuestionResponse.question:type_name -> internapi.DNSQuestion
	4, // 2: internapi.DNSQuestionResponse.response:type_name -> internapi.DNSResponse
	6, // 3: internapi.DNSResponse.expiry:type_name -> google.protobuf.Timestamp
	0, // 4: internapi.DNSResponse.type:type_name -> internapi.DNSResponse.Type
	3, // 5: internapi.ListKeysResponse.questions:type_name -> internapi.DNSQuestion
	1, // 6: internapi.InternAPI.NewContent:input_type -> internapi.NewContentRequest
	7, // 7: internapi.InternAPI.InternalListKeys:input_type -> google.protobuf.Empty
	7, // 8: internapi.InternAPI.NewContent:output_type -> google.protobuf.Empty
	5, // 9: internapi.InternAPI.InternalListKeys:output_type -> internapi.ListKeysResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_internal_pkg_internapi_internapi_proto_init() }
func file_internal_pkg_internapi_internapi_proto_init() {
	if File_internal_pkg_internapi_internapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_internapi_internapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewContentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_internapi_internapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNSQuestionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_internapi_internapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNSQuestion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_internapi_internapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DNSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_internapi_internapi_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListKeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_internapi_internapi_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_internapi_internapi_proto_goTypes,
		DependencyIndexes: file_internal_pkg_internapi_internapi_proto_depIdxs,
		EnumInfos:         file_internal_pkg_internapi_internapi_proto_enumTypes,
		MessageInfos:      file_internal_pkg_internapi_internapi_proto_msgTypes,
	}.Build()
	File_internal_pkg_internapi_internapi_proto = out.File
	file_internal_pkg_internapi_internapi_proto_rawDesc = nil
	file_internal_pkg_internapi_internapi_proto_goTypes = nil
	file_internal_pkg_internapi_internapi_proto_depIdxs = nil
}
