# Use goreman to run `go install github.com/mattn/goreman@latest`
raftkvstore1: go run ./internal/cmd/raftkvstore -id 1 -cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 -port 12380
raftkvstore2: go run ./internal/cmd/raftkvstore -id 2 -cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 -port 22380
raftkvstore3: go run ./internal/cmd/raftkvstore -id 3 -cluster http://127.0.0.1:12379,http://127.0.0.1:22379,http://127.0.0.1:32379 -port 32380
