// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: internal/pkg/raftcache/raftcache.proto

package raftcache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RaftCacheRequest_Action int32

const (
	RaftCacheRequest_LOOKUP RaftCacheRequest_Action = 0
	RaftCacheRequest_STORE  RaftCacheRequest_Action = 1
	RaftCacheRequest_DELETE RaftCacheRequest_Action = 2
)

// Enum value maps for RaftCacheRequest_Action.
var (
	RaftCacheRequest_Action_name = map[int32]string{
		0: "LOOKUP",
		1: "STORE",
		2: "DELETE",
	}
	RaftCacheRequest_Action_value = map[string]int32{
		"LOOKUP": 0,
		"STORE":  1,
		"DELETE": 2,
	}
)

func (x RaftCacheRequest_Action) Enum() *RaftCacheRequest_Action {
	p := new(RaftCacheRequest_Action)
	*p = x
	return p
}

func (x RaftCacheRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RaftCacheRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_pkg_raftcache_raftcache_proto_enumTypes[0].Descriptor()
}

func (RaftCacheRequest_Action) Type() protoreflect.EnumType {
	return &file_internal_pkg_raftcache_raftcache_proto_enumTypes[0]
}

func (x RaftCacheRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RaftCacheRequest_Action.Descriptor instead.
func (RaftCacheRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_internal_pkg_raftcache_raftcache_proto_rawDescGZIP(), []int{0, 0}
}

type RaftCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action RaftCacheRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=raftcache.RaftCacheRequest_Action" json:"action,omitempty"`
	Key    string                  `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value  string                  `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *RaftCacheRequest) Reset() {
	*x = RaftCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_raftcache_raftcache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCacheRequest) ProtoMessage() {}

func (x *RaftCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_raftcache_raftcache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCacheRequest.ProtoReflect.Descriptor instead.
func (*RaftCacheRequest) Descriptor() ([]byte, []int) {
	return file_internal_pkg_raftcache_raftcache_proto_rawDescGZIP(), []int{0}
}

func (x *RaftCacheRequest) GetAction() RaftCacheRequest_Action {
	if x != nil {
		return x.Action
	}
	return RaftCacheRequest_LOOKUP
}

func (x *RaftCacheRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RaftCacheRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RaftCacheReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // repeated string value = 2;
}

func (x *RaftCacheReply) Reset() {
	*x = RaftCacheReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_pkg_raftcache_raftcache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RaftCacheReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaftCacheReply) ProtoMessage() {}

func (x *RaftCacheReply) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pkg_raftcache_raftcache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaftCacheReply.ProtoReflect.Descriptor instead.
func (*RaftCacheReply) Descriptor() ([]byte, []int) {
	return file_internal_pkg_raftcache_raftcache_proto_rawDescGZIP(), []int{1}
}

func (x *RaftCacheReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RaftCacheReply) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_internal_pkg_raftcache_raftcache_proto protoreflect.FileDescriptor

var file_internal_pkg_raftcache_raftcache_proto_rawDesc = []byte{
	0x0a, 0x26, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x72,
	0x61, 0x66, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x72, 0x61, 0x66, 0x74, 0x63, 0x61,
	0x63, 0x68, 0x65, 0x22, 0xa3, 0x01, 0x0a, 0x10, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x22, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0a, 0x0a, 0x06, 0x4c, 0x4f, 0x4f, 0x4b, 0x55, 0x50,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a,
	0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x22, 0x36, 0x0a, 0x0e, 0x52, 0x61, 0x66,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x32, 0xd6, 0x01, 0x0a, 0x09, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12,
	0x42, 0x0a, 0x06, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x1b, 0x2e, 0x72, 0x61, 0x66, 0x74,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x63, 0x61, 0x63,
	0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x72,
	0x61, 0x66, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63,
	0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x61, 0x66, 0x74,
	0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x1b, 0x2e, 0x72, 0x61, 0x66, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66,
	0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x72, 0x61, 0x66, 0x74, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x52, 0x61, 0x66, 0x74, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x54, 0x69, 0x6d, 0x6f, 0x74, 0x68, 0x79,
	0x47, 0x75, 0x2f, 0x73, 0x74, 0x61, 0x6e, 0x66, 0x6f, 0x72, 0x64, 0x2d, 0x63, 0x73, 0x32, 0x34,
	0x34, 0x42, 0x2d, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x72, 0x61, 0x66, 0x74, 0x63,
	0x61, 0x63, 0x68, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_pkg_raftcache_raftcache_proto_rawDescOnce sync.Once
	file_internal_pkg_raftcache_raftcache_proto_rawDescData = file_internal_pkg_raftcache_raftcache_proto_rawDesc
)

func file_internal_pkg_raftcache_raftcache_proto_rawDescGZIP() []byte {
	file_internal_pkg_raftcache_raftcache_proto_rawDescOnce.Do(func() {
		file_internal_pkg_raftcache_raftcache_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_pkg_raftcache_raftcache_proto_rawDescData)
	})
	return file_internal_pkg_raftcache_raftcache_proto_rawDescData
}

var file_internal_pkg_raftcache_raftcache_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_pkg_raftcache_raftcache_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_pkg_raftcache_raftcache_proto_goTypes = []interface{}{
	(RaftCacheRequest_Action)(0), // 0: raftcache.RaftCacheRequest.Action
	(*RaftCacheRequest)(nil),     // 1: raftcache.RaftCacheRequest
	(*RaftCacheReply)(nil),       // 2: raftcache.RaftCacheReply
}
var file_internal_pkg_raftcache_raftcache_proto_depIdxs = []int32{
	0, // 0: raftcache.RaftCacheRequest.action:type_name -> raftcache.RaftCacheRequest.Action
	1, // 1: raftcache.RaftCache.Lookup:input_type -> raftcache.RaftCacheRequest
	1, // 2: raftcache.RaftCache.Store:input_type -> raftcache.RaftCacheRequest
	1, // 3: raftcache.RaftCache.Delete:input_type -> raftcache.RaftCacheRequest
	2, // 4: raftcache.RaftCache.Lookup:output_type -> raftcache.RaftCacheReply
	2, // 5: raftcache.RaftCache.Store:output_type -> raftcache.RaftCacheReply
	2, // 6: raftcache.RaftCache.Delete:output_type -> raftcache.RaftCacheReply
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_pkg_raftcache_raftcache_proto_init() }
func file_internal_pkg_raftcache_raftcache_proto_init() {
	if File_internal_pkg_raftcache_raftcache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_pkg_raftcache_raftcache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_pkg_raftcache_raftcache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RaftCacheReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_pkg_raftcache_raftcache_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pkg_raftcache_raftcache_proto_goTypes,
		DependencyIndexes: file_internal_pkg_raftcache_raftcache_proto_depIdxs,
		EnumInfos:         file_internal_pkg_raftcache_raftcache_proto_enumTypes,
		MessageInfos:      file_internal_pkg_raftcache_raftcache_proto_msgTypes,
	}.Build()
	File_internal_pkg_raftcache_raftcache_proto = out.File
	file_internal_pkg_raftcache_raftcache_proto_rawDesc = nil
	file_internal_pkg_raftcache_raftcache_proto_goTypes = nil
	file_internal_pkg_raftcache_raftcache_proto_depIdxs = nil
}
