// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: internal/pkg/raftcache/raftcache.proto

package raftcache

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RaftCacheClient is the client API for RaftCache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftCacheClient interface {
	Lookup(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error)
	Store(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error)
	Delete(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error)
}

type raftCacheClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftCacheClient(cc grpc.ClientConnInterface) RaftCacheClient {
	return &raftCacheClient{cc}
}

func (c *raftCacheClient) Lookup(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error) {
	out := new(RaftCacheReply)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Lookup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Store(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error) {
	out := new(RaftCacheReply)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftCacheClient) Delete(ctx context.Context, in *RaftCacheRequest, opts ...grpc.CallOption) (*RaftCacheReply, error) {
	out := new(RaftCacheReply)
	err := c.cc.Invoke(ctx, "/raftcache.RaftCache/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaftCacheServer is the server API for RaftCache service.
// All implementations must embed UnimplementedRaftCacheServer
// for forward compatibility
type RaftCacheServer interface {
	Lookup(context.Context, *RaftCacheRequest) (*RaftCacheReply, error)
	Store(context.Context, *RaftCacheRequest) (*RaftCacheReply, error)
	Delete(context.Context, *RaftCacheRequest) (*RaftCacheReply, error)
	mustEmbedUnimplementedRaftCacheServer()
}

// UnimplementedRaftCacheServer must be embedded to have forward compatible implementations.
type UnimplementedRaftCacheServer struct {
}

func (UnimplementedRaftCacheServer) Lookup(context.Context, *RaftCacheRequest) (*RaftCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Lookup not implemented")
}
func (UnimplementedRaftCacheServer) Store(context.Context, *RaftCacheRequest) (*RaftCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedRaftCacheServer) Delete(context.Context, *RaftCacheRequest) (*RaftCacheReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRaftCacheServer) mustEmbedUnimplementedRaftCacheServer() {}

// UnsafeRaftCacheServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftCacheServer will
// result in compilation errors.
type UnsafeRaftCacheServer interface {
	mustEmbedUnimplementedRaftCacheServer()
}

func RegisterRaftCacheServer(s grpc.ServiceRegistrar, srv RaftCacheServer) {
	s.RegisterService(&RaftCache_ServiceDesc, srv)
}

func _RaftCache_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Lookup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Lookup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Lookup(ctx, req.(*RaftCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Store(ctx, req.(*RaftCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftCache_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RaftCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftCacheServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raftcache.RaftCache/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftCacheServer).Delete(ctx, req.(*RaftCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RaftCache_ServiceDesc is the grpc.ServiceDesc for RaftCache service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftCache_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raftcache.RaftCache",
	HandlerType: (*RaftCacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Lookup",
			Handler:    _RaftCache_Lookup_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _RaftCache_Store_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RaftCache_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/pkg/raftcache/raftcache.proto",
}
